name: bounty_hub_client
description:  Client application for the Bountyhub portal

version: 1.0.0+12

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0+1
  firebase_analytics: ^7.0.1

  #localisation
  flutter_localizations:
    sdk: flutter
  flutter_sheet_localization: ^1.0.0

  bloc: ^6.1.0
  flutter_bloc: ^6.0.6

  # network
  dio: 3.0.10
  retrofit: 1.3.4
  json_serializable: 3.3.0
  pretty_dio_logger: 1.1.1
  url_launcher: ^5.7.8

  # code gen
  build_runner: ^1.10.0
  retrofit_generator: 1.3.4+1

  # view / model
  formz: ^0.3.1
  equatable: ^1.2.5
  webview_flutter: ^1.0.7

  # logger
  logger: ^0.9.4

  uni_links: ^0.4.0

  # storage
  flutter_secure_storage: ^3.3.5
  hive_flutter: ^0.3.1
  shared_preferences: ^0.5.12+4

  # string utils
  enum_to_string: ^1.0.13
  flutter_linkify: ^4.0.2

  # image utils
  cached_network_image: ^2.3.3
  image_picker: ^0.6.7+21

  # platform utils
  path_provider: ^1.6.24
  flutter_countdown_timer: ^2.1.0

  cupertino_icons: ^1.0.0
  country_code_picker:
    path: ./plugins/country_code_picker-1.6.2
  polygon_clipper: ^1.0.2
  flutter_html: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.10.0

  app_gen:
    path: plugins/app_gen

  flutter_sheet_localization_generator: ^1.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-Thin.ttf
           weight: 100
         - asset: assets/fonts/Montserrat-Light.ttf
           weight: 300
         - asset: assets/fonts/Montserrat-Regular.ttf
           weight: 400
         - asset: assets/fonts/Montserrat-Medium.ttf
           weight: 500
         - asset: assets/fonts/Montserrat-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Montserrat-Bold.ttf
           weight: 700
         - asset: assets/fonts/Montserrat-Black.ttf
           weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
