name: bounty_hub_client
description:  Client application for the Bountyhub portal

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  bloc: ^6.0.0
  flutter_bloc: ^6.0.0

  # network
  dio: 3.0.10
  retrofit: 1.3.4
  json_serializable: 3.3.0
  pretty_dio_logger: 1.1.1
  url_launcher: ^5.7.8

  # code gen
  build_runner: ^1.10.0
  retrofit_generator: 1.3.4+1

  # view / model
  formz: ^0.3.1
  equatable: ^1.2.5
  webview_flutter: ^1.0.3

  # logger
  logger: ^0.9.4

  # storage
  flutter_secure_storage: ^3.3.5
  hive_flutter: ^0.3.1

  # string utils
  enum_to_string: ^1.0.13

  # platform utils
  path_provider: ^1.6.24

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.10.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - lang/en.json

  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-Thin.ttf
           weight: 100
         - asset: assets/fonts/Montserrat-Light.ttf
           weight: 300
         - asset: assets/fonts/Montserrat-Regular.ttf
           weight: 400
         - asset: assets/fonts/Montserrat-Medium.ttf
           weight: 500
         - asset: assets/fonts/Montserrat-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Montserrat-Bold.ttf
           weight: 700
         - asset: assets/fonts/Montserrat-Black.ttf
           weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
